# ActiveRecord extension to get more from PostgreSQL.
gem 'pg_power', '1.3.0'

# acts_as_paranoid is Active Record (~>3.2) plugin which allows you to
# hide and restore records without actually deleting them.
gem 'acts_as_paranoid', '0.4.1'

# oauth is a RubyGem for implementing both OAuth clients and servers in Ruby applications.
gem 'oauth', '0.4.7'

# twitter is a Ruby interface to the Twitter API.
gem 'twitter', '4.5.0'

# Koala is a Facebook library for Ruby, supporting the Graph API (including the batch requests and photo uploads),
# the REST API, realtime updates, test users, and OAuth validation.
gem 'koala', '1.6.0'

# Nokogiri (鋸) is an HTML, XML, SAX, and Reader parser.
# Among Nokogiri’s many features is the ability to search documents via XPath or CSS3 selectors.
gem 'nokogiri','1.5.6'

# Resque is a Redis-backed Ruby library for creating background jobs,
# placing those jobs on multiple queues, and processing them later.
gem 'resque', '1.23.0', :require => 'resque/server'

# meta_search is Allows simple search forms to be created against an AR3
# model and its associations, has useful view helpers for sort links and
# multiparameter fields as well.
gem 'meta_search', '1.1.3'

# will_paginate provides a simple API for performing paginated queries with
# Active Record, DataMapper and Sequel, and includes helpers for rendering
#  pagination links in Rails, Sinatra and Merb web apps.
gem 'will_paginate', '3.0.4'

# Ruby 1.9.2 compatible soap4r library
gem 'soap4r-ruby1.9', '2.0.5'

# Delicious SOAP for the Ruby community
gem 'savon', '2.1.0'
