gem 'pg_comment'  # DBのコメント付与

# 課題管理機能
gem 'acts_as_paranoid'  # 論理削除

# 外部出力機能
gem 'oauth'
gem 'twitter'
gem 'koala'

# xml 表示
gem 'nokogiri'

# 非同期処理
gem 'resque', require: 'resque/server'

gem 'meta_search'

gem 'will_paginate'
