# encoding: utf-8
Area.delete_all # 全件削除

Area.create(:area_code => '01', :name => '石巻／山の手地区', :remarks => '', :polygon => '{}')
Area.create(:area_code => '02', :name => '石巻／石巻地区', :remarks => '', :polygon => '{}')
Area.create(:area_code => '03', :name => '石巻／門脇地区', :remarks => '', :polygon => '{}')
Area.create(:area_code => '04', :name => '石巻／釜大街道地区', :remarks => '', :polygon => '{}')
Area.create(:area_code => '05', :name => '石巻／住吉地区', :remarks => '', :polygon => '{}')
Area.create(:area_code => '06', :name => '石巻／山下地区', :remarks => '', :polygon => '{}')
Area.create(:area_code => '07', :name => '石巻／虻田地区', :remarks => '', :polygon => '{}')
Area.create(:area_code => '08', :name => '石巻／湊地区', :remarks => '', :polygon => '{}')
Area.create(:area_code => '09', :name => '石巻／渡波地区', :remarks => '', :polygon => '{}')
Area.create(:area_code => '10', :name => '石巻／稲井地区', :remarks => '', :polygon => '{}')
Area.create(:area_code => '11', :name => '石巻／荻浜地区', :remarks => '', :polygon => '{}')
Area.create(:area_code => '12', :name => '石巻／田代地区', :remarks => '', :polygon => '{}')
Area.create(:area_code => '13', :name => '石巻／石巻市内', :remarks => '', :polygon => '{}')
Area.create(:area_code => '14', :name => '河北地区', :remarks => '', :polygon => '{}')
Area.create(:area_code => '15', :name => '雄勝地区', :remarks => '', :polygon => '{}')
Area.create(:area_code => '16', :name => '河南地区', :remarks => '', :polygon => '{}')
Area.create(:area_code => '17', :name => '桃生地区', :remarks => '', :polygon => '{}')
Area.create(:area_code => '18', :name => '北上地区', :remarks => '', :polygon => '{}')
Area.create(:area_code => '19', :name => '牡鹿地区', :remarks => '', :polygon => '{}')
