# encoding: utf-8
# 削除（100以下）
ActiveRecord::Base.connection.execute(%{DELETE FROM trackers WHERE id <= 100})

# シーケンス初期化（100以下の場合のみ）
ActiveRecord::Base.connection.execute(%{SELECT setval( 'trackers_id_seq' ,CASE WHEN (SELECT MAX(id) FROM trackers) >= 100 THEN (SELECT MAX(id) FROM trackers) ELSE 100 END)})

# 登録
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (1, 1, '避難勧告・指示情報（公共情報コモンズ配信用）', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (2, 30, '避難勧告・指示情報（APPLIC配信用）', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (3, 2, '避難所情報（公共情報コモンズ配信用）', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (4, 31, '避難所情報（APPLIC配信用）', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (5, 3, '気象情報（気象等環境変化）', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (6, 4, '気象情報（警報・注意報）', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (7, 5, '河川情報（気象等環境変化）', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (8, 6, '河川情報（警報・注意報）', false, true, 0)})

ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (9, 16, '【消防庁様式】災害対策本部設置報告', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (10, 17, '【消防庁様式】被害要約報告（概況）', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (11, 18, '【消防庁様式】被害要約報告（状況）', false, true, 0)})

ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (12, 7, '【被害報告】人的', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (13, 8, '【被害報告】住家建物', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (14, 33, '【被害報告】非住家建物', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (15, 9, '【被害報告】道路', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (16, 10, '【被害報告】橋梁', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (17, 11, '【被害報告】上水道', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (18, 12, '【被害報告】下水道', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (19, 13, '【被害報告】ガス設備', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (20, 14, '【被害報告】通信網', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (21, 34, '【被害報告】高等学校', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (22, 35, '【被害報告】中学校', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (23, 36, '【被害報告】小学校', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (24, 37, '【被害報告】幼稚園', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (25, 38, '【被害報告】保育所', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (26, 39, '【被害報告】災害弱者関連施設', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (27, 40, '【被害報告】医療施設', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (28, 41, '【被害報告】災害重要施設', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (29, 15, '【被害報告】その他', false, true, 0)})

ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (30, 22, '道路交通事故に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (31, 23, '路上故障車に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (32, 24, '路上障害物に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (33, 26, '道路火災に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (34, 67, '救急・救命の要請', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (35, 68, '海上に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (36, 69, '河川に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (37, 70, '広域圏災害に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (38, 28, '被災者からの要望（生活全般）', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (39, 71, '被災者からの要望（食料）', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (40, 29, '被災者からの要望（物資・資材）', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (41, 48, 'その他の災害関連情報', false, true, 0)})

ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (42, 20, '【広報-交通】道路通行規制に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (43, 21, '【広報-交通】道路渋滞に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (44, 25, '【広報-交通】道路工事に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (45, 27, '【広報-交通】道路路面状況に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (46, 42, '【広報-交通】鉄道の運行に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (47, 72, '【広報-交通】バスの運行に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (48, 73, '【広報-交通】航空路の運行に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (49, 74, '【広報-交通】船舶路の運行に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (50, 75, '【広報-交通】その他公共交通の運行に関する情報', false, true, 0)})

ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (51, 55, '【広報-ライフライン】給水に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (52, 50, '【広報-ライフライン】電気に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (53, 43, '【広報-ライフライン】上水道に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (54, 44, '【広報-ライフライン】下水道に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (55, 45, '【広報-ライフライン】ガスに関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (56, 46, '【広報-ライフライン】通信網に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (57, 51, '【広報-ライフライン】臨時災害放送に関する情報', false, true, 0)})

ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (58, 52, '【広報-生活情報】行政手続きに関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (59, 62, '【広報-生活情報】安置所に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (60, 63, '【広報-生活情報】災害習得物に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (61, 60, '【広報-生活情報】炊き出し・物資配布に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (62, 61, '【広報-生活情報】入浴サービスに関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (63, 66, '【広報-生活情報】営業店舗に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (64, 59, '【広報-生活情報】医療に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (65, 56, '【広報-生活情報】健康・福祉・介護に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (66, 54, '【広報-生活情報】学校・幼稚園・保育所に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (67, 57, '【広報-生活情報】環境に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (68, 58, '【広報-生活情報】防犯に関する情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (69, 64, '【広報-生活情報】ボランティアの支援を受けたい方への情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (70, 65, '【広報-生活情報】ボランティア活動をしたい方への情報', false, true, 0)})
ActiveRecord::Base.connection.execute(%{INSERT INTO trackers (position, id, name, is_in_chlog, is_in_roadmap, fields_bits) VALUES (71, 53, '【広報-生活情報】その他の被災者支援に関する情報', false, true, 0)})
