production:
  adapter: postgresql
  database: redmine_pg_dev
  host: 127.0.0.1
  username: postgres
  password: postgres
  encoding: utf8

development:
  adapter: postgresql
  database: redmine_pg_dev
  host: 127.0.0.1
  username: dev
  password: devdev
  encoding: utf8

